### ISSUE TITLE
Digraphs fails to build on GCC 15.1.1

### ISSUE THREAD

**Issue by saffronmciver** [digraphs/Digraphs#763]
The following error occurs when building with GCC 15.1.1, I think since warnings `-Wstrict-prototypes` and `-Wdeprecated-non-prototype` are now errors in C23, now default in GCC 15.1.1. I tried downgrading to GCC 13.3.1 and I was able to build Digraphs. Planarity 4.0 by itself also builds fine on GCC 15.1.1 since it is declaring the argument types for the `graphFunctionTable.h` declarations.

```
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDFSUtils.c: In function ‘gp_SortVertices’:
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDFSUtils.c:147:13: error: too many arguments to function ‘theGraph->functions.fpSortVertices’; expected 0, have 1
  147 |      return theGraph->functions.fpSortVertices(theGraph);
      |             ^~~~~~~~                           ~~~~~~~~
In file included from extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphStructures.h:15,
                 from extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graph.h:14,
                 from extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDFSUtils.c:9:
extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphFunctionTable.h:54:16: note: declared here
   54 |         int  (*fpSortVertices)();
      |                ^~~~~~~~~~~~~~
   GAC     extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDrawPlanar.c => gen/extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDrawPlanar.o
make: *** [Makefile.gappkg:119: gen/extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphDFSUtils.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by fingolfin** [comment]
The problem is the declaration in `extern/edge-addition-planarity-suite-Version_3.0.1.0/c/graphFunctionTable.h:54`
```C
        int  (*fpSortVertices)();
```
presumably this could be fixed by changing it to
```C
        int  (*fpSortVertices)(graphP theGraph);
```
but there are many other similar prototypes in that struct:
```C
typedef struct
{
        // These function pointers allow extension modules to overload some of
        // the behaviors of protected functions.  Only advanced applications
        // will overload these functions
    	int  (*fpEmbeddingInitialize)();
        void (*fpEmbedBackEdgeToDescendant)();
        void (*fpWalkUp)();
        int  (*fpWalkDown)();
        int  (*fpMergeBicomps)();
        void (*fpMergeVertex)();
        int  (*fpHandleInactiveVertex)();
        int  (*fpHandleBlockedBicomp)();
        int  (*fpEmbedPostprocess)();
        int  (*fpMarkDFSPath)();

        int  (*fpCheckEmbeddingIntegrity)();
        int  (*fpCheckObstructionIntegrity)();

        // These function pointers allow extension modules to overload some
        // of the behaviors of gp_* function in the public API
        int  (*fpInitGraph)();
        void (*fpReinitializeGraph)();
        int  (*fpEnsureArcCapacity)();
        int  (*fpSortVertices)();

        int  (*fpReadPostprocess)();
        int  (*fpWritePostprocess)();

        void (*fpHideEdge)();
        void (*fpRestoreEdge)();
        int  (*fpHideVertex)();
        int  (*fpRestoreVertex)();
        int  (*fpContractEdge)();
        int  (*fpIdentifyVertices)();

} graphFunctionTable;
```
presumably all of these should be adjusted in some way.

**Comment by wilfwilson** [comment]
Thanks @fingolfin. We've been discussing this sort of thing in https://github.com/graph-algorithms/edge-addition-planarity-suite/issues/147. 🙂

**Comment by james-d-mitchell** [comment]
Thanks @john-boyer-phd  @fingolfin and @wilfwilson, looking forward to a new version of EAPS!
